# Generated by Django 4.1 on 2024-03-08 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MentalHealth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
    ]
