# Generated by Django 4.1 on 2024-03-10 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MentalHealth", "0004_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="available_seats",
        ),
        migrations.RemoveField(
            model_name="event",
            name="booked_by",
        ),
    ]
