# Generated by Django 4.1 on 2024-03-17 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MentalHealth", "0008_delete_booking_delete_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("9:00 AM - 10:00 AM", "9:00 AM - 10:00 AM"),
                            ("10:00 AM - 11:00 AM", "10:00 AM - 11:00 AM"),
                            ("11:00 AM - 12:00 PM", "11:00 AM - 12:00 PM"),
                            ("1:00 PM - 2:00 PM", "1:00 PM - 2:00 PM"),
                            ("2:00 PM - 3:00 PM", "2:00 PM - 3:00 PM"),
                            ("3:00 PM - 4:00 PM", "3:00 PM - 4:00 PM"),
                        ],
                        max_length=100,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
