# Generated by Django 4.1 on 2024-03-17 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("MentalHealth", "0009_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
